#!/usr/bin/env node
// scripts/render.mjs
// Build Markdown leaderboards from data/plugins.json.
// Zero deps. Node >= 20.
//
// Outputs:
//   README.md         (only the <!-- BEGIN:BOT --> ... <!-- END:BOT --> section is overwritten)
//   docs/index.md     full sortable table
//   docs/categories/<category>.md
//   docs/trending.md  top-N newest (created_at desc)
//   docs/maintained.md top-N recently pushed (pushed_at desc)

import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CATEGORIES, VERDICT_BADGE, isListed, categorize } from './lib/shared.mjs';

const ROOT  = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA  = join(ROOT, 'data', 'plugins.json');
const DOCS  = join(ROOT, 'docs');
const README = join(ROOT, 'README.md');

function row(item) {
  const cat = item._category ?? categorize(item);
  const safeDesc = (item.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const badge = VERDICT_BADGE[item.verified] ?? '❓';
  return `| #${item._rank} | [${item.repo}](${item.html_url}) | ⭐ ${item.stars} | ${badge} | ${safeDesc} | \`${cat}\` |`;
}

function tableHeader() {
  return '| # | Repo | Stars | Verified | Description | Category |\n|---|---|---|---|---|---|';
}

function buildTable(items) {
  return [tableHeader(), ...items.map(row)].join('\n');
}

function frontmatterBlock(meta) {
  const { total, snapshot_at, source_query, schema_version } = meta;
  return [
    '<!-- BEGIN:BOT -->',
    `<!-- Auto-generated by scripts/render.mjs — DO NOT EDIT BELOW. -->`,
    ``,
    `Snapshot: \`${snapshot_at}\` · Indexed: **${total}** repos · Schema: v${schema_version} · Query: \`${source_query}\``,
    ``,
  ].join('\n');
}

async function main() {
  const data = JSON.parse(await readFile(DATA, 'utf-8'));

  // Decorate once with category + rank
  const decorated = data.items
    .slice()
    .sort((a, b) => b.stars - a.stars)
    .map((it, i) => ({ ...it, _rank: i + 1, _category: categorize(it) }));

  const listed   = decorated.filter(isListed).map((it, i) => ({ ...it, _rank: i + 1 }));
  const excluded = decorated.filter(it => it.verified === 'excluded');
  const rejected = decorated.filter(it => it.verified === 'suspect' || it.verified === 'error');
  const vs = data.verified_summary ?? {};

  // Detect whether a previous snapshot exists (growth board activates day 2).
  let hasHistory = false;
  try {
    const files = (await readdir(join(ROOT, 'data', 'history'))).filter(f => f.endsWith('.json'));
    hasHistory = files.length >= 2;
  } catch { /* no history dir yet */ }

  await mkdir(join(DOCS, 'categories'), { recursive: true });

  // ---- README.md (overwrite only the BOT section) ----
  const readmePath = README;
  let readme = '';
  try { readme = await readFile(readmePath, 'utf-8'); } catch { /* missing, fine for first build */ }

  const links = [
    '[docs/index.md](docs/index.md) for the full sortable list',
    '[docs/categories/](docs/categories/) per category',
    '[docs/trending.md](docs/trending.md) for newest',
    '[docs/maintained.md](docs/maintained.md) for recently active',
    hasHistory ? '[docs/growth.md](docs/growth.md) for fastest growing' : null,
    '[docs/suspects.md](docs/suspects.md) for quarantined repos',
  ].filter(Boolean).join(', ');

  const bot = [
    frontmatterBlock(data),
    `Verification: ✅ ${vs.verified ?? 0} verified · 🟡 ${vs.likely ?? 0} likely · ❌ ${vs.suspect ?? 0} suspect (quarantined)${vs.error ? ` · ⚠️ ${vs.error} error` : ''}`,
    ``,
    `## Top 50 by stars (verified plugins only)`,
    ``,
    buildTable(listed.slice(0, 50)),
    ``,
    `See ${links}.`,
    ``,
    `<!-- END:BOT -->`,
  ].join('\n');

  const begin = '<!-- BEGIN:BOT -->';
  const end   = '<!-- END:BOT -->';
  let next;
  if (readme.includes(begin) && readme.includes(end)) {
    const i = readme.indexOf(begin);
    const j = readme.indexOf(end) + end.length;
    next = readme.slice(0, i) + bot + '\n' + readme.slice(j);
  } else {
    next = (readme ? readme.trimEnd() + '\n\n' : '') + bot + '\n';
  }
  await writeFile(readmePath, next);

  // ---- docs/index.md ----
  await writeFile(join(DOCS, 'index.md'),
    `# All ${listed.length} verified plugins by stars\n\n` +
    `_Auto-generated from \`data/plugins.json\`. Squatted repos are quarantined in [suspects.md](suspects.md)._\n\n` +
    buildTable(listed) + '\n'
  );

  // ---- per-category (verified only) ----
  for (const cat of CATEGORIES) {
    const list = listed.filter(it => it._category === cat);
    if (!list.length) continue;
    const re = list.map((it, i) => ({ ...it, _rank: i + 1 }));
    await writeFile(join(DOCS, 'categories', `${cat}.md`),
      `# ${cat} plugins (${re.length})\n\n` +
      buildTable(re) + '\n'
    );
  }

  // ---- trending (newest by created_at, verified only) ----
  const newest = listed.slice()
    .sort((a, b) => (b.created_at || '').localeCompare(a.created_at || ''))
    .slice(0, 30)
    .map((it, i) => ({ ...it, _rank: i + 1 }));
  if (newest.length) {
    await writeFile(join(DOCS, 'trending.md'),
      `# Newest 30 verified plugins\n\n` +
      buildTable(newest) + '\n'
    );
  }

  // ---- maintained (recently pushed, verified only) ----
  const active = listed.slice()
    .sort((a, b) => (b.pushed_at || '').localeCompare(a.pushed_at || ''))
    .slice(0, 30)
    .map((it, i) => ({ ...it, _rank: i + 1 }));
  if (active.length) {
    await writeFile(join(DOCS, 'maintained.md'),
      `# Most recently pushed verified plugins (top 30)\n\n` +
      buildTable(active) + '\n'
    );
  }

  // ---- suspects quarantine ----
  const susp = rejected.map((it, i) => ({ ...it, _rank: i + 1 }));
  const suspRows = susp.map(it =>
    `| #${it._rank} | [${it.repo}](${it.html_url}) | ⭐ ${it.stars} | ${VERDICT_BADGE[it.verified] ?? '❓'} | ${(it.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`
  ).join('\n');
  const exclRows = excluded.map(it =>
    `| [${it.repo}](${it.html_url}) | ⭐ ${it.stars} | ${(it.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`
  ).join('\n');
  await writeFile(join(DOCS, 'suspects.md'),
    `# Quarantined repos (${susp.length})\n\n` +
    `These repos carry the \`dsh-plugin\` topic but show no evidence of being a real DSH plugin ` +
    `(no \`"dsh"\` field in package.json, no \`cordis.patch.yml\` / \`dsh.plugin.json\`, no \`dsh plugin --profile\` install docs). ` +
    `They are excluded from every leaderboard. If one of them is yours and is genuine, add the plugin manifest or install docs and it will be re-listed on the next refresh.\n\n` +
    `| # | Repo | Stars | Verdict | Description |\n|---|---|---|---|---|\n` +
    suspRows + '\n\n' +
    (excluded.length
      ? `## Manually excluded (${excluded.length})\n\nNot plugins by definition (e.g. the DSH host itself). Tracked for transparency, never listed.\n\n` +
        `| Repo | Stars | Description |\n|---|---|---|\n` + exclRows + '\n'
      : '')
  );

  // ---- growth (star delta vs previous daily snapshot; activates from day 2) ----
  let growthGenerated = false;
  try {
    const histDir = join(ROOT, 'data', 'history');
    const files = (await readdir(histDir)).filter(f => f.endsWith('.json')).sort();
    if (files.length >= 2) {
      const prev = JSON.parse(await readFile(join(histDir, files[files.length - 2]), 'utf-8'));
      const prevStars = new Map((prev.items ?? []).map(i => [i.repo, i.stars]));
      const grown = listed
        .map(it => ({ ...it, _delta: it.stars - (prevStars.get(it.repo) ?? it.stars) }))
        .filter(it => it._delta > 0)
        .sort((a, b) => b._delta - a._delta)
        .slice(0, 30)
        .map((it, i) => ({ ...it, _rank: i + 1 }));
      if (grown.length) {
        const rows = grown.map(it => {
          const safeDesc = (it.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
          const badge = VERDICT_BADGE[it.verified] ?? '❓';
          return `| #${it._rank} | [${it.repo}](${it.html_url}) | ⭐ ${it.stars} | +${it._delta} | ${badge} | ${safeDesc} | \`${it._category}\` |`;
        }).join('\n');
        await writeFile(join(DOCS, 'growth.md'),
          `# Fastest growing verified plugins (top 30, vs ${files[files.length - 2].slice(0, 10)})\n\n` +
          `| # | Repo | Stars | Δ | Verified | Description | Category |\n|---|---|---|---|---|---|---|\n` +
          rows + '\n'
        );
        growthGenerated = true;
      }
    }
  } catch { /* history unavailable — growth board stays absent */ }

  console.log(`OK rendered ${listed.length} listed / ${rejected.length} quarantined across ${
    new Set(listed.map(it => it._category)).size
  } categories${growthGenerated ? ' (+growth)' : ''}`);
}

main().catch((e) => {
  console.error(`[render] FAIL: ${e.message}`);
  process.exit(1);
});
